import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('link', { name: 'Account', exact: true }).click();
  await page.locator('#login').click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('user');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('user');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Entities' }).click();
  await page.getByRole('link', { name: 'Bank Account' }).click();
  await page.getByRole('button', { name: 'Create a new Bank Account' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('new_label_bankaccount_one');
  await page.getByRole('spinbutton', { name: 'Balance' }).click();
  await page.getByRole('spinbutton', { name: 'Balance' }).fill('0.0');
  await page.getByLabel('User').selectOption('2: Object');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Entities' }).click();
  await page.getByRole('link', { name: 'Label' }).click();
  await page.getByRole('button', { name: 'Create a new Label' }).click();
  await page.getByRole('textbox', { name: 'Label' }).click();
  await page.getByRole('textbox', { name: 'Label' }).fill('new_label_one');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Entities' }).click();
  await page.getByRole('link', { name: 'Operation' }).click();
  await page.getByRole('button', { name: 'Create a new Operation' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('new_label_operation_one');
  await page.getByRole('spinbutton', { name: 'Amount' }).click();
  await page.getByRole('spinbutton', { name: 'Amount' }).fill('0.0');
  await page.getByLabel('Bank Account').selectOption({ label: 'new_label_bankaccount_one' });
  await page.getByLabel('Label').selectOption({ label: 'new_label_one' });
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('Date').click();
  await page.getByText('Date').click();
  await page.getByRole('cell', { name: 'new_label_operation_one' }).first().click();
});
