# prometheus/prometheus.yml
global:
  scrape_interval: 15s # Intervalo de recolección de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'pushgateway-ngrok'
    static_configs:
      - targets: ['profound-abnormally-monkfish.ngrok-free.app']

  - job_name: 'github_actions_metrics'
    static_configs:
      - targets: ['github_actions_exporter:9999'] # Reemplazar con tu endpoint o exporter

  #App Local
  - job_name: 'spring_app_local'
    metrics_path: /management/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - target_label: phase
        replacement: 'local'

  #App Render
  - job_name: 'spring_app_render'
    metrics_path: /management/prometheus
    scheme: https
    static_configs:
      - targets: ['jhipster-sample-app.onrender.com']
    relabel_configs:
      - target_label: phase
        replacement: 'render'
