# prometheus/prometheus.yml
global:
  scrape_interval: 15s # Intervalo de recolección de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'github_actions_metrics'
    static_configs:
      - targets: ['github_actions_exporter:9100'] # Reemplazar con tu endpoint o exporter
