# prometheus/prometheus.yml
global:
  scrape_interval: 15s # Intervalo de recolección de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'github_actions_metrics'
    static_configs:
      - targets: ['github_actions_exporter:9999'] # Reemplazar con tu endpoint o exporter
