# prometheus/prometheus.yml
global:
  scrape_interval: 15s # Intervalo de recolección de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['profound-abnormally-monkfish.ngrok-free.app']

  - job_name: 'github_actions_metrics'
    static_configs:
      - targets: ['localhost:9999'] # Reemplazar con tu endpoint o exporter
